---
- hosts: localhost
  tasks:
    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if Swarm is already initialized
      command: docker info --format '{{ .Swarm.LocalNodeState }}'
      register: swarm_status
      changed_when: false
      failed_when: swarm_status.stdout not in ['inactive', 'active']

    - name: Initialize Docker Swarm (if not already a manager)
      command: docker swarm init --advertise-addr {{ ansible_host }}
      when: swarm_status.stdout == "inactive"
      register: swarm_init

    - name: Get worker join token
      command: docker swarm join-token -q worker
      register: worker_token
      when: swarm_status.stdout == "active"
      changed_when: false
      delegate_to: "{{ groups['manager'][0] }}"
      run_once: true

    - name: Join Docker Swarm as a worker
      command: docker swarm join --token {{ worker_token.stdout }} {{ hostvars[groups['manager'][0]].ansible_host }}:2377
      when: swarm_status.stdout == "inactive" and 'manager' not in group_names
