---
- hosts: localhost
  vars:
    unifi_hostname: "{{ host }}"
    admin_email: "{{ alert_email }}"
    user: "srvradmin"
    unifi_service: "unifi"
    unifi_dir: "/var/lib/unifi"
    java_dir: "/usr/lib/unifi"
    keystore: "{{ unifi_dir }}/keystore"
    le_mode: true
    le_live_dir: "/etc/letsencrypt/live"
    priv_key: "{{ le_live_dir }}/{{ unifi_hostname }}/privkey.pem"
    chain_file: "{{ le_live_dir }}/{{ unifi_hostname }}/fullchain.pem"
    alias: "unifi"
    password: "aircontrolenterprise"
    target_dir: "/etc/letsencrypt/live"

  tasks:
    - name: Install required dependencies
      apt:
        name:
          - ca-certificates
          - apt-transport-https
          - gnupg
          - curl
          - ufw
        state: present

    - name: Add UniFi repository
      shell: |
        echo 'deb [ arch=amd64,arm64 ] https://www.ui.com/downloads/unifi/debian stable ubiquiti' > /etc/apt/sources.list.d/100-ubnt-unifi.list
        wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ui.com/unifi/unifi-repo.gpg

    - name: Add MongoDB repository
      shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" > /etc/apt/sources.list.d/mongodb-org-7.0.list

    - name: Allow necessary firewall ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 8080
        - 8443
        - 80

    - name: Install MongoDB and UniFi Controller
      apt:
        update_cache: yes
        name:
          - mongodb-org
          - unifi
        state: present

    - name: Install Certbot
      apt:
        name:
          - certbot
          - python3-certbot-apache
        state: present

    - name: Request SSL certificate with Certbot
      command: >
        certbot --apache --email "{{ admin_email }}" --no-eff-email --agree-tos -n -d "{{ unifi_hostname }}" --quiet

    - name: Set permissions for Let's Encrypt directory
      file:
        path: "{{ target_dir }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0770"
        recurse: yes

    - name: Verify Let's Encrypt directory permissions
      command: "ls -ld {{ target_dir }}"

    - name: View Let's Encrypt directory contents
      command: "ls {{ target_dir }}"

    - name: Restart UniFi Controller
      service:
        name: "{{ unifi_service }}"
        state: restarted
