---
- hosts: localhost
  vars:
    unifi_hostname: "{{ host }}"
    unifi_service: "unifi"
    unifi_dir: "/var/lib/unifi"
    java_dir: "/usr/lib/unifi"
    keystore: "/var/lib/unifi/keystore"
    le_mode: true  # Set to false if not using Let's Encrypt
    le_live_dir: "/etc/letsencrypt/live"
    priv_key: "/etc/letsencrypt/live/{{ unifi_hostname }}/privkey.pem"
    chain_file: "/etc/letsencrypt/live/{{ unifi_hostname }}/fullchain.pem"
    alias: "unifi"
    password: "aircontrolenterprise"

  tasks:
    - name: Stop UniFi Controller
      service:
        name: "{{ unifi_service }}"
        state: stopped

    - name: Backup existing keystore
      copy:
        src: "{{ keystore }}"
        dest: "{{ keystore }}.bak"
        remote_src: yes
      ignore_errors: yes

    - name: Export SSL certificate to PKCS12 file
      command:
        cmd: >
          openssl pkcs12 -export \
          -in "{{ chain_file }}" \
          -inkey "{{ priv_key }}" \
          -out "/tmp/unifi.p12" \
          -passout pass:"{{ password }}" \
          -name "{{ alias }}"

    - name: Remove previous certificate from keystore
      command:
        cmd: >
          keytool -delete -alias "{{ alias }}" -keystore "{{ keystore }}" -deststorepass "{{ password }}"
      ignore_errors: yes

    - name: Import new SSL certificate into keystore
      command:
        cmd: >
          keytool -importkeystore \
          -srckeystore "/tmp/unifi.p12" \
          -srcstoretype PKCS12 \
          -srcstorepass "{{ password }}" \
          -destkeystore "{{ keystore }}" \
          -deststorepass "{{ password }}" \
          -destkeypass "{{ password }}" \
          -alias "{{ alias }}" -trustcacerts

    - name: Remove temporary PKCS12 file
      file:
        path: "/tmp/unifi.p12"
        state: absent

    - name: Start UniFi Controller
      service:
        name: "{{ unifi_service }}"
        state: started
